name: Build and Push Python App to Docker Hub

on:
  push:
    branches:
      - main  # يتم التنفيذ عند الدفع إلى الفرع الرئيسي

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. التحقق من المستودع
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. تسجيل الدخول إلى Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      # 3. بناء الصورة ورفعها إلى Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # المسار إلى Dockerfile
          push: true  # رفع الصورة بعد بنائها
          tags: ${{ secrets.DOCKER_USERNAME }}/python-app:latest  # اسم الصورة والإصدار
